import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import Head from "next/head";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&family=Noto+Sans&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <div className="overflow-y-clip">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
